name: excel_to_json
description: A package that allows you to transform your excel to JSON
version: 0.0.2-dev.1
homepage: https://github.com/vitoramaral10/excel_to_json

environment:
  sdk: ">=2.12.1 <3.0.0"

dependencies:
  excel: ^2.0.0-null-safety-3
  file_picker: ^5.0.1
  flutter:
    sdk: flutter
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null